#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo 'Styling, testing and building your project...'

# check prettier 
npm run check-format || {
    echo 'Please run "npm run format" to format your code before committing.'
    exit 1
}

# check eslint
npm run check-lint || {
    echo 'eslint check failed. Make the required changes before committing. Add change and try to commit again.'
    exit 1
}

# check tsconfig
npm run check-types || {
    echo 'TypeScript check failed. Make the required changes before committing. Add change and try to commit again.'
    exit 1
}

npm run build || {
    echo 'Build failed. Make the required changes before committing. Add change and try to commit again.'
    exit 1
}

echo "success commit"